alias: Controller Level
description: ""
mode: single
triggers:
  - event_type: zwave_js_notification
    event_data:
      command_class_name: Multilevel Switch
      event_type_label: Start level change
    trigger: event
conditions: []
actions:
  - data:
      ctrl_device_id: "{{trigger.event.data['device_id']}}"
      direction: "{{trigger.event.data['direction']}}"
    action: script.updatelevitoncontrollers
