alias: Controller Activation
description: ""
trigger:
  - platform: device
    device_id: <<< put your device_id here
    domain: zwave_js
    type: event.value_notification.scene_activation
    property: sceneId
    property_key: null
    endpoint: 0
    command_class: 43
    subtype: Endpoint 0
>>> copy/paste "platform" block above for any additional controllers
condition: []
action:
  - service: script.updatelevitoncontrollers
    data:
      ctrl_device_id: "{{ trigger.event.data['device_id'] }}"
      value: "{{ trigger.event.data['value'] }}"
mode: single
