alias: Switch Activation
description: ""
triggers:
  - type: changed_states
    device_id: <<< put your switch device_id
    entity_id: <<< put your switch entity_id
    domain: switch
    trigger: device
  - type: changed_states
    device_id: <<< put your light device_id
    entity_id: <<< put your light entity_id
    domain: light
    trigger: device
>>> copy/paste "type" block above for any additional switches/lights
conditions: []
actions:
  - data:
      switch_entity_id: "{{ trigger['entity_id'] }}"
    action: script.updatelevitoncontrollers
mode: queued
